import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FooterPage from "./components/footer";
import HeaderPage from "./components/header";
import NavPage from "./components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <HeaderPage />
      <NavPage />
      <section className={inter.className}>{children}</section>
      <FooterPage />
      </body>
    </html>
  );
}
